import { describe, expect, it } from '@jest/globals';
import { DecisionCore } from '../decisioncore.js';
import { Personality, Morale, AgentBelief, BeliefEvidence, ReputationBook } from '../socialcore.js';
import { routeCost, raidUtility, FactionState } from '../macrocore.js';
import { InteractionCore } from '../interactioncore.js';
import { AdvisoryGate } from '../advisorygate.js';
import { Market, RouteNetwork, SocietyCore } from '../societycore.js';

describe('Fear AI runtime foundations', () => {
    it('blocks prerequisites and returns trace explanations', () => { const result = new DecisionCore({ random: () => 0 }).evaluate({ alive: false, fear: 1 }, [{ id: 'attack', prerequisites: ['alive'], considerations: [{ name: 'fear', value: 'fear' }] }, { id: 'observe', considerations: [{ name: 'calm', value: 1 }] }]); expect(result.selected).toBe('observe'); expect(result.candidates[0].blockers).toContain('alive'); });
    it('keeps personality and morale bounded and separate', () => { const personality = new Personality({ neuroticism: 1, conscientiousness: 0 }); expect(personality.fearSensitivity()).toBe(1.5); const morale = new Morale(.3); morale.update({ fear: 1, losses: 100 }); expect(morale.value).toBeGreaterThanOrEqual(.2); expect(morale.canFreeze()).toBe(true); });
    it('updates beliefs from evidence and aggregates reputation', () => { const belief = new AgentBelief('danger', false); belief.addEvidence(new BeliefEvidence({ valueEstimate: true, confidence: 1, sourceTrust: 1, directObservation: true })); expect(belief.estimate).toBe(true); const reputation = new ReputationBook(); reputation.update('actor', 0, 2); reputation.update('actor', 1, 1); expect(reputation.get('actor')).toBeCloseTo(1 / 3); });
    it('calculates perceived route and raid values', () => { expect(routeCost({ travelTime: 5, perceivedDanger: 2 }, { fearSensitivity: 2 })).toBe(9); expect(raidUtility({ expectedLoot: 10, expectedLosses: 3 })).toBe(7); expect(new FactionState({ fear: 1, threatPerception: 1 }).escalationLevel()).toBeGreaterThan(0); });
    it('filters interactions and rejects unauthorized advisory actions', () => { const core = new InteractionCore(); const vampire = { id: 'v', type: 'VAMPIRE' }; const human = { id: 'h', type: 'HUMAN' }; expect(core.validate('transform', vampire, human, { targetAlive: false }).valid).toBe(false); expect(new AdvisoryGate({ interactionCore: core }).validate({ action: 'transform' }, { type: 'HUMAN' }, human).approved).toBe(false); });
    it('propagates rumors, changes markets, and selects by perceived danger', () => { const society = new SocietyCore(); const rumor = society.rumors.publish({ claim: 'road-danger', valueEstimate: true, confidence: .9 }); const recipient = { beliefs: new Map(), sourceTrust: 1 }; society.rumors.spread(rumor, [recipient]); expect(recipient.beliefs.get('road-danger').estimate).toBe(true); const market = new Market({ prices: { grain: 1 } }); market.update({ demand: { grain: 10 }, supply: { grain: 0 } }); expect(market.prices.grain).toBeGreaterThan(1); const route = society.routes.chooseRoute([{ id: 'safe', travelTime: 10, perceivedDanger: 0 }, { id: 'dangerous', travelTime: 1, perceivedDanger: 10 }], { fearSensitivity: 2 }); expect(route.id).toBe('safe'); });
    it('computes crime, justice, legitimacy, and migration consequences', () => { const society = new SocietyCore(); expect(society.resolveCrime({ reward: 10, apprehension: 1, sanction: 20 })).toBe(-10); expect(society.reportCrime({ legitimacy: 1, trust: 1, duty: 1 })).toBe(1); expect(society.updateLegitimacy(.5, { injustice: 1 })).toBeLessThan(.5); expect(society.shouldMigrate({ fear: 1, routeDanger: 1, foodSecurity: 0, legitimacy: 0 })).toBe(true); });
});
