/**
 * Canonical Fear AI Protocol v1.0.0 - Types & Enums
 */

export const PROTOCOL_VERSION = '1.0.0';

export const MESSAGE_TYPES = Object.freeze({
    // Client to Server
    HANDSHAKE_REQUEST: 'HANDSHAKE_REQUEST',
    REGISTER_AGENT: 'REGISTER_AGENT',
    UNREGISTER_AGENT: 'UNREGISTER_AGENT',
    OBSERVATION_DISPATCH: 'OBSERVATION_DISPATCH',
    BATCH_TICK_REQUEST: 'BATCH_TICK_REQUEST',
    STEP_REQUEST: 'STEP_REQUEST',
    RESET_REQUEST: 'RESET_REQUEST',
    SAVE_SNAPSHOT_REQUEST: 'SAVE_SNAPSHOT_REQUEST',
    LOAD_SNAPSHOT_REQUEST: 'LOAD_SNAPSHOT_REQUEST',
    SET_PACING_OVERRIDE: 'SET_PACING_OVERRIDE',

    // Server to Client
    HANDSHAKE_RESPONSE: 'HANDSHAKE_RESPONSE',
    AGENT_STATE_UPDATE: 'AGENT_STATE_UPDATE',
    BATCH_TICK_RESPONSE: 'BATCH_TICK_RESPONSE',
    SNAPSHOT_RESPONSE: 'SNAPSHOT_RESPONSE',
    ERROR_RESPONSE: 'ERROR_RESPONSE'
});

export const STIMULUS_TYPES = Object.freeze([
    'PREDATOR',
    'SOUND',
    'LIGHT_FLICKER',
    'GORE_OBJECT',
    'SCREAM',
    'ENVIRONMENTAL_DREAD',
    'ANOMALY'
]);

export const ERROR_CODES = Object.freeze({
    INVALID_PROTOCOL_VERSION: 'INVALID_PROTOCOL_VERSION',
    MALFORMED_MESSAGE: 'MALFORMED_MESSAGE',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    AGENT_ALREADY_REGISTERED: 'AGENT_ALREADY_REGISTERED',
    AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
    SIMULATION_ERROR: 'SIMULATION_ERROR',
    SNAPSHOT_ERROR: 'SNAPSHOT_ERROR'
});
